### ISSUE TITLE
Can't run sam deploy -g

### ISSUE THREAD

**Issue by jasontt33** [aws-samples/serverless-trivia-game#31]
When trying to run sam deploy --guided from the backend directory, an error pops up: 
 Error: Invalid value for '--parameter-overrides':   is not in valid format. It must look something like 'ParameterKey=KeyPairName,ParameterValue=MyKey ParameterKey=InstanceType,ParameterValue=t1.micro' or 'KeyPairName=MyKey InstanceType=t1.micro'

Environment:
MacOS = Monteray
Node v = 18.7.0
SAM CLI, version 1.53.0
cdk version 2.34.2 (build 7abcbc6)
@vue/cli 5.0.8
aws-cli/2.1.9 Python/3.7.4 Darwin/21.4.0 exe/x86_64 prompt/off

**Comment by timjbruce** [comment]
Working on updated install docos. It looks like there was a revert due to some build failure reports for SAM that might be causing this to occur. Hopefully will have updates by tomorrow.

**Comment by timjbruce** [comment]
Fixed by pull #33
