### ISSUE TITLE
Error: Failed to create changeset for the stack

### ISSUE THREAD

**Issue by ahmedalalousi** [aws-samples/serverless-trivia-game#34]
I get all the way through the sam deploy part, and receive the following output:

`Error: Failed to create changeset for the stack: sam-app, An error occurred (ValidationError) when calling the CreateChangeSet operation: 1 validation error detected: Value '[CAPABILITY_NAMED_IAM, CAPABILIYT_AUTO_EXPAND, CAPABILITY_IAM]' at 'capabilities' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [CAPABILITY_AUTO_EXPAND, CAPABILITY_NAMED_IAM, CAPABILITY_IAM]]`

Deployment values are:

`Deploying with following values
	===============================
	Stack name                   : sam-app
	Region                       : eu-west-2
	Confirm changeset            : False
	Disable rollback             : False
	Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-c77eh4r0us07
	Capabilities                 : ["CAPABILITY_NAMED_IAM", "CAPABILIYT_AUTO_EXPAND", "CAPABILITY_IAM"]
	Parameter overrides          : {"IoTEndpoint": "a7v3b6r2xpl3d-ats.iot.eu-west-2.amazonaws.com", "LogRetentionDays": "14", "ResourceGroupPrefix": "GameService", "EMFNamespace": "STS", "S3BufferInterval": "60", "S3BufferSize": "5", "SourceStreamSize": "1"}
	Signing Profiles             : {}`

Environment:

OS: macOS Monterey
NodeJS version: v16.13.0
SAM CLI version: 1.53.0
aws-cli/2.1.23 Python/3.7.4 Darwin/21.6.0 exe/x86_64 prompt/off

**Comment by djo10** [comment]
There is a typo `CAPABILIYT_AUTO_EXPAND`

It should be `CAPABILITY_AUTO_EXPAND`

**Comment by ahmedalalousi** [comment]
> There is a typo `CAPABILIYT_AUTO_EXPAND`
> 
> It should be `CAPABILITY_AUTO_EXPAND`

Thanks; corrected, but now a different set of errors are thrown. Starts with:
`CREATE_FAILED                      AWS::CloudFormation::Stack         HTTP                               Embedded stack
                                                                                                         arn:aws:cloudformation:eu-
                                                                                                         west-2:950591086666:stack/sam-
                                                                                                         app-HTTP-K8EAZAVMOOLR/0bd77670-1
                                                                                                         988-11ed-bdc2-0ae1583edacc was
                                                                                                         not successfully created: The
                                                                                                         following resource(s) failed to
                                                                                                         create: [DAXParams].
CREATE_FAILED                      AWS::CloudFormation::Stack         IOT                                Resource creation cancelled
ROLLBACK_IN_PROGRESS               AWS::CloudFormation::Stack         sam-app                            The following resource(s) failed
                                                                                                         to create: [HTTP, IOT]. Rollback
                                                                                                         requested by user.`

Then everything rolls back and resources deleted. [Full error log is here.](http://ahmedalalousimybuckt.s3-website.eu-west-2.amazonaws.com/Initiating%20deployment%20log.txt)

**Comment by djo10** [comment]
> > There is a typo `CAPABILIYT_AUTO_EXPAND`
> > It should be `CAPABILITY_AUTO_EXPAND`
> 
> Thanks; corrected, but now a different set of errors are thrown. Starts with: `CREATE_FAILED AWS::CloudFormation::Stack HTTP Embedded stack arn:aws:cloudformation:eu- west-2:950591086666:stack/sam- app-HTTP-K8EAZAVMOOLR/0bd77670-1 988-11ed-bdc2-0ae1583edacc was not successfully created: The following resource(s) failed to create: [DAXParams]. CREATE_FAILED AWS::CloudFormation::Stack IOT Resource creation cancelled ROLLBACK_IN_PROGRESS AWS::CloudFormation::Stack sam-app The following resource(s) failed to create: [HTTP, IOT]. Rollback requested by user.`
> 
> Then everything rolls back and resources deleted. [Full error log is here.](http://ahmedalalousimybuckt.s3-website.eu-west-2.amazonaws.com/Initiating%20deployment%20log.txt)

Have you done CDK bootstrapping?

**Comment by ahmedalalousi** [comment]
> > > There is a typo `CAPABILIYT_AUTO_EXPAND`
> > > It should be `CAPABILITY_AUTO_EXPAND`
> > 
> > 
> > Thanks; corrected, but now a different set of errors are thrown. Starts with: `CREATE_FAILED AWS::CloudFormation::Stack HTTP Embedded stack arn:aws:cloudformation:eu- west-2:950591086666:stack/sam- app-HTTP-K8EAZAVMOOLR/0bd77670-1 988-11ed-bdc2-0ae1583edacc was not successfully created: The following resource(s) failed to create: [DAXParams]. CREATE_FAILED AWS::CloudFormation::Stack IOT Resource creation cancelled ROLLBACK_IN_PROGRESS AWS::CloudFormation::Stack sam-app The following resource(s) failed to create: [HTTP, IOT]. Rollback requested by user.`
> > Then everything rolls back and resources deleted. [Full error log is here.](http://ahmedalalousimybuckt.s3-website.eu-west-2.amazonaws.com/Initiating%20deployment%20log.txt)
> 
> Have you done CDK bootstrapping?

I foolishly assumed the template would take care of that; did the CDK bootstrapping, and now waiting for the deployment to complete .. sleeping at "CREATE_COMPLETE                    AWS::CloudFormation::Stack         IOT"

I'll update the thread with the outcome.
