### ISSUE TITLE
Idempotent Workflow Bug: Repeated Money Adjustments in MoneyAdjustFunction

### ISSUE THREAD

**Issue by NullPointer4096** [aws-samples/serverless-trivia-game#67]
The [MoneyAdjustFunction](https://github.com/aws-samples/serverless-trivia-game/blob/3f9fa70a3f765a0815f134e129d06d85a15eeef9/backend/Functions/Main/money_adjust/app.js#L55) function is invoked upon receiving an SNS message to increase or decrease the amount of "money" in a player's wallet. If an error occurs after the player record is created or updated and hence the function retries, the money will be adjusted for the second time, which is undesired. The triggering error may include software, hardware, or network errors that would cause the asynchronously invoked function to retry. The expected behavior is that the function should not apply repeated adjustments upon retry if the money was adjusted in a previous run.

The key is determining whether the adjustment was made in a previous run. One solution is having a `LastRequestId` field in the player's record for holding `context.aws_request_id`'s, which is constant across retries. If [the query](https://github.com/aws-samples/serverless-trivia-game/blob/3f9fa70a3f765a0815f134e129d06d85a15eeef9/backend/Functions/Main/money_adjust/app.js#L32) finds no record, create a player record with Item = { playerName, amount, LastRequestId=context.aws_request_id} at L46. If the query finds a record, and only if `Item.LastRequestId != context.aws_request_id`,  update the money amount, and set `Item.LastRequestId=context.aws_request_id`. This approach ensures that the money adjustments are applied only once, even if the function is retried.

**Comment by timjbruce** [comment]
Thanks for the call out on idempotency. This hasn't been a big focus as of yet, but I will upgrade the urgency! This problem also is present in progress.

There are chances that there are multiple messages could be in flight for this, so checking only the last request_id value will not completely resolve the problem. A solution similar to Lambda PowerTools for Java should be targeted to prevent multiple message idempotency issues.

**Comment by timjbruce** [comment]
Feature added
